version: "3.9"
services:
  postgres:
    image: postgres:13.2-alpine
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 30s
      timeout: 30s
      retries: 3
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USERNAME=postgres
      - POSTGRES_DB=tickets_challenge
    networks:
      - fullstack
    volumes:
        - database_postgres:/var/lib/postgresql/data  
    ports:
      - "5434:5432"
